friends = ["Kevin", "Karen", "Jim","Kim","Sim","Jim"]
friends_1 = ["Kevin", 1, "Jim"]
lucky_numbers=[4, 8, 15, 16, 17, 18]
print(friends[0])
print(friends[2])
print(friends[-1])
print(friends[-2])
print(friends[1:3])
print(friends[1])
#friends.extend(lucky_numbers)
print(friends)
friends.insert(1, "Kelly")
print(friends)
friends.remove("Jim")
print(friends)
#friends.clear()
print (friends)
#it pops out the last element
friends.pop()
print(friends)
print(friends.index("Kevin"))
print(friends.index("Kim"))
#print(friends.index("Mona"))
print(friends.count("Jim"))
print(lucky_numbers.sort())
#friends.sort()
print(friends)
friends2= friends.copy()
print(friends2)
